### ISSUE TITLE
Cannot add GitHub and Codeberg profile

### ISSUE THREAD

**Issue by Cameo007** [rafaelmardojai/forge-sparks#28] opened 2024-02-13 22:36 UTC
When I try to add an GitHub or Codeberg account Forge Sparks sort of times out with an unexpected error. As `flatpak run com.mardojai.ForgeSparks` directly detaches after launch I can't provide any error messages.

**Comment by rukshn** [comment] 2024-04-04 05:08
I also can't seem to connect GitHub and it returns the following log when running `run com.mardojai.ForgeSparks`

```
(com.mardojai.ForgeSparks:2): Gtk-CRITICAL **: 07:05:18.884: gtk_accessible_text_get_contents: assertion 'end >= start' failed
com.mardojai.ForgeSparks-Message: 07:05:25.908: https://api.github.com/user response resulted in 200
com.mardojai.ForgeSparks-Message: 07:05:26.163: Gio.DBusError: org.freedesktop.DBus.Error.ServiceUnknown
_promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:454:44
main@resource:///com/mardojai/ForgeSparks/main.js:28:24
run@resource:///org/gnome/gjs/modules/script/package.js:207:19
@file:///app/bin/forge-sparks:28:43
@file:///app/bin/forge-sparks:34:6
### Promise created here: ###
saveAccount@resource:///com/mardojai/ForgeSparks/model/accountsManager.js:147:42
_addAccount@resource:///com/mardojai/ForgeSparks/widgets/accountDialog.js:315:32
async*_onSave@resource:///com/mardojai/ForgeSparks/widgets/accountDialog.js:290:18
main@resource:///com/mardojai/ForgeSparks/main.js:28:24
run@resource:///org/gnome/gjs/modules/script/package.js:207:19
@file:///app/bin/forge-sparks:28:43
@file:///app/bin/forge-sparks:34:6
```

**Comment by rafaelmardojai** [comment] 2024-04-04 12:42
@rukshn seems to fail in the secret saving process. Are you using the Flatpak? If not, do you have `libsecret` installed?

**Comment by rukshn** [comment] 2024-04-04 15:17
@rafaelmardojai I am using Flatpak. And seems I have `libsecret` installed when I check with Yast

**Comment by rafaelmardojai** [comment] 2024-04-04 15:20
@rukshn Just to be sure, do you have `xdg-desktop-portal-gnome` installed?

**Comment by rukshn** [comment] 2024-04-05 12:24
@rafaelmardojai i did not had it installed, but after installing through Yast I still get it, do I have to install it though flatpak?

**Comment by rukshn** [comment] 2024-04-08 12:02
@rafaelmardojai yes this seems to work, but i think it would be better if this can be run within flatpak

**Comment by rafaelmardojai** [comment] 2024-04-08 12:20
@rukshn right, but now we know the problem is about libsecret having problems when sandboxed. 

And this seems to only happen in some setups, since I can't reproduce from Fedora 39.

**Comment by rafaelmardojai** [comment] 2024-09-01 13:58
The actual problem is the one reported on #19, so closing this.

**Closed by rafaelmardojai** 2024-09-01 13:58 UTC
Labels: bug
